#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-0 --mode 1920x1080 --rate 144 --rotate right --left-of DP-2 &
xrandr --output DP-2 --mode 3440x1440 --rate 60 --primary &
sleep 2
xrandr --output DP-2 --mode 3440x1440 --rate 144 --primary &
#feh --bg-fill --randomize ~/Pictures/wallpapers/003.jpeg &
discord &
steam -silent &
sleep 2
$HOME/.config/polybar/launch.sh &
whatpulse --delaystartup --closedwindow &
picom &
wal -i Pictures/wallpapers/010.jpeg &
pywal-discord &
obs --startreplaybuffer --minimize-to-tray &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          16
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

